### ISSUE TITLE
Checar se o json de sucesso está no formato esperado

### ISSUE THREAD

**Issue by filhodanuvem** [vmeazevedo/Postal_Address_Finder#4]
Essa issue foi aberta durante um [vídeo do canal queroserprogramador](https://youtu.be/k3goTujHLg8), a intenção é incentivar que outro inscrito resolva essa issue, então se segure @vmeazevedo 🤣 . 

🇧🇷 Eu notei que quando passamos o cep  `36880000`que representa mais de uma rua, a api retorna status code 200 mas o formato do json é diferente do esperado, causando o erro da imagem abaixo. Nós precisamos checar se o formato do json é diferente do esperado e mostrar um erro agradável como `Não foi possível acessar o CEP por favor verifique seu número e digite novamente.`. 

![](https://i.imgur.com/tX03NRT.png) 

🇬🇧 I've noticed that when we pass the cep `36880000`, which represents more than one street the api does return 200 as status code but the json format is different than the expected, causing an error (image above). We need to check the json format somehow and show graceful errors such as `Não foi possível acessar o CEP por favor verifique seu número e digite novamente.`.

**Comment by vmeazevedo** [comment]
Issue solucionada por: https://github.com/wallis6n no pull request: Arrumando o problema do json inválido.
