### ISSUE TITLE
Atualizar a imagem do funcionamento

### ISSUE THREAD

**Issue by pixelmorto** [vmeazevedo/Postal_Address_Finder#6]
Como o output agora é diferente recomendo atualizar a imagem :>

**Comment by vmeazevedo** [comment]
A atualização será implementada ao final do dia. (Y)
Obrigado por sua contribuição!!!

**Comment by vmeazevedo** [comment]
![cep_novo](https://user-images.githubusercontent.com/40063504/79053440-bf10e600-7c13-11ea-8ed3-224732866f23.PNG)
Ao rodar o código via um executável, o código da cor se corrompe e não é apresentado.

**Comment by wallis6n** [comment]
Como o binário é feito?

**Comment by vmeazevedo** [comment]
Também não, é gerado a mesma "resposta" .

**Comment by pixelmorto** [comment]
Acabei de verificar aqui, esse problema parece ser algo no cmd do windows, vou tentar procurar uma solução aqui.

**Comment by filhodanuvem** [comment]
Talvez o @wallis6n  tenha usado bash como shell e o @vmeazevedo usa powershell. Estou vendo pela imagem que códigos `\e[31m` não foram interpretados. Recomendo ou remover ou tentar estudar como fazer esses códigos funcionarem em ambos os shells (não sei se é possivel).

Ops, comentei isso na mesma hora que o wallison 😅 .

Algumas referências: 
https://misc.flogisoft.com/bash/tip_colors_and_formatting
https://stackoverflow.com/questions/50611733/powershell-color-schemes

**Comment by vmeazevedo** [comment]
Por hora vou retirar rsrs só pra deixar o programa rodando liso como ta. 
Mas @wallis6n se puder, abre um issue disso para o pessoal que vir após ver o vídeo do @cloudson possa dar uma olhada tbm! O que acha?

**Comment by pixelmorto** [comment]
Concordo, acho que a melhor opção é remover por hora mesmo, quando conseguir algo aqui faço um pull.

**Comment by vmeazevedo** [comment]
![cep_new](https://user-images.githubusercontent.com/40063504/79054220-94c22700-7c19-11ea-9bc9-29643b4a962f.PNG)

Atualização do README realizada.

**Comment by filhodanuvem** [comment]
Me parece uma boa decisão por enquanto @vmeazevedo . 
Eu não tenho windows aqui, pode tentar algo pra mim @vmeazevedo , coloque 

```python
#!/bin/bash
```

na primeira linha do script python e teste novamente por favor? (sorry por comentar na issue fechada, movemos para outra depois).

**Comment by vmeazevedo** [comment]
Sem problemas rs
@cloudson rodei aqui e ainda obtenho o mesmo resultado.

**Comment by filhodanuvem** [comment]
Por enquanto não estou convencido de que haja uma forma de usar os mesmos códigos nos dois shell. 

https://superuser.com/questions/1259900/how-to-colorize-the-powershell-prompt 

enquanto no bash fazemos `\e` no powershell é esperado ` 'e`. 

Talvez uma forma seja tentar identificar o shell atual, em OS Unix temos a variavel `$SHELL`, se essa variável não existir no windows, já da pra supor que estamos no powershell. E para cada caso usar um escape sequence diferente   🤷🏾‍♂️.

**Comment by pixelmorto** [comment]
Parece existir um módulo chamado colorama que faz exatamente isso.

**Comment by filhodanuvem** [comment]
Acho melhor fechar a issue entao e se for interessante pro @vmeazevedo, usamos esse modulo para resolver o "problema".
